name: CoreProtectReloadedCommon
version: 0.1.0
main: com.github.kisaragieffective.coreprotectreloaded.common.CoreProtectReloadedCommon
website: https://github.com/KisaragiEffective/CoreProtectReloaded